// S0〜S3 のUI文言を一元管理する。画面コンポーネントは直書きせず本モジュールを参照すること。
// トーン: 神社・おみくじの世界観を保ちつつ、参加者に意図が正確に伝わる表現。

export const copy = {
  common: {
    timeout: "通信がタイムアウトしました。電波状況を確認の上、もう一度お試しください。",
    rateLimited: "リクエストが混み合っています。しばらく待ってからお試しください。",
  },
  site: {
    title: "BDSF 寄り道おみくじ",
    festival: "BDSF 2026",
    shrineName: "寄り道神社",
    boothLabel: "御神籤授与所",
  },
  top: {
    heading: "今日の寄り道を授かろう",
    lead: "今の気分を教えてください。AIがあなたにぴったりの『寄り道』を導き出します。",
    guidance: "迷ったら、いま一番近いものを直感で選んでください。",
    privacyNote: "※入力内容と写真はAIによる判定のみに使用され、保存されることはありません。",
    drawProgressLabel: "今日の寄り道印",
    drawReady: "準備が整いました。今日の運勢を引いてみよう！",
    drawRemaining: (rest: number) => `あと${rest}つ選ぶと、おみくじを引けます`,
    mascotIdle: "一緒に運勢を探そう",
    mascotRemaining: (rest: number) => `あと${rest}つ教えてね`,
    mascotReady: "準備OK！運勢を引こう",
    submit: "鈴緒を引いて授かる",
    submitBusy: "御神籤を整えています...",
    questions: { mood: "気分", goal: "目的", companion: "同行者" },
  },
  drawing: {
    messages: [
      "今日の寄り道を選んでいます...",
      "気持ちを読み取っています...",
      "ぴったりのスポットを探しています...",
      "運勢を書き上げています...",
    ] as string[],
  },
  result: {
    badge: "今日の寄り道",
    destinationKicker: "最初に向かう企画",
    fallbackBadge: "公式データから提案",
    fallbackNoticeTitle: "案内係からのお知らせ",
    fallbackNoticeBody: "案内所が混み合っているため、公式企画から一枚を選びました。",
    fallbackToast: "公式企画データからおすすめを選びました",
    nextAction: "現地のお題を見る",
    retrySame: "同じ条件で別企画",
    changeAnswer: "回答を変える",
    share: "結果をシェア",
    sharing: "シェアを準備しています...",
    shareOpened: "シェアを開きました",
    shareCopied: "結果をクリップボードにコピーしました",
    shareCopyFailed: "共有テキストのコピーに失敗しました",
    error: "おみくじを引けませんでした。電波状況を確認の上、もう一度鈴を鳴らしてみてください。",
  },
  mission: {
    headingPrefix: "現地ミッション",
    progressLabel: (done: number) => `印 ${done}/3（授与・なぞなぞ・フォト）`,
    riddleSubmit: "答え合わせをする",
    riddleCorrect: "いい発見！その調子で会場を巡ってみよう。",
    riddleFallbackCorrect: "いい発見！その調子で会場を巡ってみよう。",
    riddleFallbackHint: "答えは現地で探してみよう。見つけた瞬間がミッション達成！",
    riddleGentle: "やさしい答え合わせに切り替えました",
    photoCta: "お題の一枚を奉納する",
    photoSuccess: (title: string, comment: string) =>
      `見事！『${title}』の印を授かりました。（${comment}）`,
    photoFallbackTitle: "今日のきらめきを発見！",
    photoFallbackComment:
      "いい発見だね！写真に残したその瞬間が、今日の学園祭をもっと特別にしてくれるよ。",
    photoFallbackToast: "発見スタンプを作りました",
    manualCta: "現地に着いた・やってみた",
    completeCta: "印がそろった！交換へ進む",
    checkRewardCta: "交換所を確認する",
  },
  reward: {
    heading: "集めた印をノベルティに交換",    lead: "寄り道御朱印帳の記録数に応じて、好きな特典を選べます。",
    countLabel: "現在の発見カード",
    ticketLabel: "授与所 受付番号",
    ticketHint: "交換を申し込むとき、この番号をスタッフにお見せください。",
    staffKeyLabel: "スタッフ承認キー",
    staffKeyPlaceholder: "スタッフが入力してください",
    staffKeyHint: "スタッフ端末で承認キーを入力してから、授与を確定します。",
    stickerName: "ステッカー",
    toteName: "トートバッグ",
    stickerCondition: "1件以上",
    toteCondition: "3件以上",
    available: "交換できます",
    stickerRemaining: "あと1件で交換できます",
    toteRemaining: (rest: number) => `あと${rest}件で交換できます`,
    claimedOnDevice: "この端末では交換済みです",
    exchange: "交換する",
    recording: "記録中",
    conditionUnmet: "条件未達成",
    exchanged: "交換済み",
    stickerRecorded: "ステッカーの交換を記録しました",
    toteRecorded: "トートバッグの交換を記録しました",
    showToStaff: "交換ボタンを押したら、この画面をブーススタッフに見せてください。",
    backToTop: "寄り道おみくじへ戻る",
    boothBusy: "授与所が混み合っています。画面を閉じずにスタッフへお声がけください。",
  },
  memories: {
    open: "思い出を開く",
    empty: "発見カメラで写真を1枚撮ると、ここに思い出をまとめられます。",
  },
} as const;
