create table if not exists public.novelty_claims (
  id bigint generated by default as identity primary key,
  visitor_id text not null,
  novelty_kind text not null check (novelty_kind in ('sticker', 'tote')),
  discovery_count integer not null check (discovery_count >= 0),
  claimed_at timestamptz not null default timezone('utc'::text, now()),
  unique (visitor_id, novelty_kind)
);

alter table public.novelty_claims enable row level security;
